# NAME : Ritvik Khandelwal
# SAP ID : 60002180081
# CLASS : TE EXTC 2

# NUMPY

In [2]:
list=[1,1.1,'hi',None]
for i in list:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'NoneType'>


In [3]:
len(list)

4

In [5]:
l=[1,2,3]
for i in l:
    print(type(i))
sum(l)/len(l)

<class 'int'>
<class 'int'>
<class 'int'>


2.0

In [6]:
l=['hi,bye','hello']

In [7]:
l.sort()
l

['hello', 'hi,bye']

In [8]:
import numpy as np

In [13]:
a=np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [10]:
print(a.shape)

(3,)


In [11]:
print(a[0],a[1],a[2])

1 2 3


In [18]:
b=np.array([[1,2],[3,4]])
print(b)
print(b.shape)

[[1 2]
 [3 4]]
(2, 2)


In [15]:
print(b[0,0],b[0,1],b[1,1])

1 2 4


In [17]:
c=np.array([[1,2],[3,4],[5,6]])
print(c)
print(c.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [20]:
d=np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
e=np.ones((4,2))
print(e)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
f=np.full((2,2),9)
print(f)

[[9 9]
 [9 9]]


In [23]:
q=np.random.random((3,3))
print(q)

[[0.52522016 0.0625529  0.20993063]
 [0.57837255 0.75105577 0.0882055 ]
 [0.28985857 0.64791579 0.16568357]]


In [24]:
h=np.array([[1,2,3,4],[5,6,7,8],[9,19,11,12]])
print(h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 19 11 12]]


In [27]:
i=h[:2,1:3]
j=h[1:3,1:]
k=h[1:3,1:3]

print(i)
print(j)
print(k)

[[2 3]
 [6 7]]
[[ 6  7  8]
 [19 11 12]]
[[ 6  7]
 [19 11]]


In [28]:
j=np.array([1,2])
print(j.dtype)

int32


In [29]:
k=np.array([1.0,2.0])
print(k.dtype)

float64


In [30]:
l=np.array([1.0,2.0],dtype=np.int64)
print(l.dtype)

int64


In [31]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)

In [32]:
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [33]:
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


In [34]:
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]


In [35]:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [36]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]
